### ISSUE TITLE
[Question] Could mint seeds be changed to extend ItemSeeds?

### ISSUE THREAD

**Issue by Belgabor** [defeatedcrow/AppleMilkTea2_1.7.10#27]
We want to include AgriCraft in our mod pack. According to the author, mint would be supported automatically if the mint seed class would extend ItemSeeds. Would that be possible?

AgriCraft, if you haven't heard of it, reimplements the IC2 crop system in a separate mod.

**Comment by defeatedcrow** [comment]
Thank you for your feedback!
I think it is very good suggestion, therefore, I will begin the corresponding work. Perhaps I think that take several days.

**Comment by Belgabor** [comment]
No hurry, thank you very much!

**Comment by Belgabor** [comment]
Thanks for implementing it, although there seems to be an issue when the crop grows. I can put the seeds on the crops fine, but it crashes as soon as it grows.

    java.lang.ArrayIndexOutOfBoundsException: 7
	at mods.defeatedcrow.common.block.plants.BlockMintCrop.func_149691_a(BlockMintCrop.java:164)
	at com.InfinityRaider.AgriCraft.tileentity.TileEntityCrop.getPlantIcon(TileEntityCrop.java:295)
	at com.InfinityRaider.AgriCraft.renderers.RenderCrop.renderWorldBlock(RenderCrop.java:31)
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118)
	at net.minecraft.src.FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1530)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Belgabor** [comment]
I tested a bit slower this time, it doesn't happen on the first growth, but on a later stage. I'm not 100% sure, but I think they try to grow beyond fully grown stage.

**Comment by defeatedcrow** [comment]
Oh! This is going to by my mistake, it was referring to the outside of the array of icons.
Because the cause is found, correct at the time of the next update.
I thank you for your report.

※ This is a digression ...
Mint crop has metadata 3 at maximum growth. This is different from vanilla wheat (maximum growth metadata 7).
I think this specification difference is causing the problem.

And thank your wonderful job, and I expect.
If cooperation is required, I will cooperate to it by modification of AMT2. (For example, such as replacing the protected method in public.) I accept the issue at any time.

**Comment by defeatedcrow** [comment]
This problem has been fixed in Version2.2a.
If any problems is found again, I would to fix it.

**Comment by Belgabor** [comment]
Yes, it doesn't crash any more, thanks!
Unfortunately it also doesn't visually grow any more as well. It works, you can harvest it, but it always looks freshly planted. Both on crops, but also if planted normally on farmland.

**Comment by defeatedcrow** [comment]
Oh! I'm sorry!
There was a mistake in the specified icon. I will fix soon.

**Comment by Belgabor** [comment]
Works perfectly now in 2.2c, thanks a lot!

**Comment by Belgabor** [comment]
Works fine, so I'll close this.
