### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by LatentDesire** [defeatedcrow/AppleMilkTea2_1.7.10#59]
---- Minecraft Crash Report ----
// You're mean.

Time: 11/9/15 7:51 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mods/defeatedcrow/common/tile/appliance/TileProsessor
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: mods/defeatedcrow/common/tile/appliance/TileProsessor
	at mods.defeatedcrow.common.MaterialRegister.addMachines(MaterialRegister.java:962)
	at mods.defeatedcrow.common.MaterialRegister.load(MaterialRegister.java:238)
	at mods.defeatedcrow.common.DCsAppleMilk.preInit(DCsAppleMilk.java:518)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more
Caused by: java.lang.ClassNotFoundException: mods.defeatedcrow.common.tile.appliance.TileProsessor
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Caused by: java.lang.NoClassDefFoundError: mods/defeatedcrow/common/tile/appliance/MachineBase
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 41 more
Caused by: java.lang.ClassNotFoundException: mods.defeatedcrow.common.tile.appliance.MachineBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 202861008 bytes (193 MB) / 579227648 bytes (552 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCH	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCH	AppleMilkCore{1.1.0} [AppleMilkCore] (minecraft.jar) 
	UCH	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) 
	UCH	gasesCore{1.6.2} [Glenn's Gases Core] (minecraft.jar) 
	UCH	gasesFrameworkCore{1.1.2} [Gases Framework Core] (minecraft.jar) 
	UCH	NotEnoughItems{1.0.3.74} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
	UCH	PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore] (minecraft.jar) 
	UCH	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCH	debug{1.0} [debug] (denseores-1.6.2.jar) 
	UCH	abyssalcraft{1.8.9.6} [AbyssalCraft] (AbyssalCraft-1.7.10-1.8.9.6.jar) 
	UCH	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCE	DCsAppleMilk{1.7.10_2.8k} [Apple&Milk&Tea!] (AppleMilkTea2-1.7.10_2.8k.jar) 
	UCE	DCsNEIPluginAMT{1.7.10_1.0a} [NEIPluginForAMT] (AppleMilkTea2-1.7.10_2.8k.jar) 
	UCH	aquaticabyss{1.1.1} [Aquatic Abyss] (AquaticAbyss-1.7.10-1.1.1.jar) 
	UCH	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCH	HardcoreEnderExpansion{1.8.4} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.4.jar) 
	UCH	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCH	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCH	Forestry{4.1.1.46} [Forestry for Minecraft] (forestry_1.7.10-4.1.1.46.jar) 
	UCH	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V9b.jar) 
	UCH	ChromatiCraft{1.0} [ChromatiCraft] (ChromatiCraft 1.7.10 V9b.jar) 
	UCH	clockworkphase{1.7.10_1.0f} [Clockwork Phase] (clockworkphase-1.7.10_1.0f.jar) 
	UCH	cookingbook{1.0.134} [Cooking for Blockheads] (cookingbook-mc1.7.10-1.0.134.jar) 
	UCH	DummyCore{1.13} [DummyCore] (DummyCore1.13.jar) 
	UCH	etfuturum{1.4.4} [Et Futurum] (Et Futurum-1.4.4.jar) 
	UCH	evilcraft{0.9.1} [EvilCraft] (EvilCraft-1.7.10-0.9.1.jar) 
	UCH	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCH	gasesFramework{1.1.2} [Gases Framework] (gasesFramework-1.7.10-1.1.2.jar) 
	UCH	gases{1.6.2} [Glenn's Gases] (gases-1.7.10-1.6.2.jar) 
	UCH	Railcraft{9.8.0.0} [Railcraft] (Railcraft_1.7.10-9.8.0.0.jar) 
	UCH	ImmersiveEngineering{0.6.0} [Immersive Engineering] (ImmersiveEngineering-0.6.0.jar) 
	UCH	Mimicry{1.7.x_1492_1.0.10} [Mimicry] (Mimicry-1.7.10_1492_1.0.10c.jar) 
	UCH	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10k.jar) 
	UCH	PneumaticCraft{1.11.19-141} [PneumaticCraft] (PneumaticCraft-1.7.10-1.11.19-141-universal.jar) 
	UCH	progressiveautomation{1.6.27} [Progressive Automation] (ProgressiveAutomation-1.7.10-1.6.27.jar) 
	UCH	RandomThings{2.2.4} [Random Things] (RandomThings-2.2.4.jar) 
	UCH	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0.jar) 
	UCH	xreliquary{1.2} [Reliquary] (Reliquary-1.2.jar) 
	UCH	SSTOW{1.7.10-0.1-RC9-7} [Soul Shards: The Old Ways] (SoulShards-TOW-1.7.10-0.1-RC9-7.jar) 
	UCH	StorageDrawers{1.7.10-1.6.2} [Storage Drawers] (StorageDrawers-1.7.10-1.6.2.jar) 
	UCH	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCH	denseores{1.0} [Dense Ores] (denseores-1.6.2.jar) 
	GL info: ' Vendor: 'Intel' Version: '1.4.0 - Build 8.14.10.2093' Renderer: 'Intel Pineview Platform'
	Mantle Environment: Environment healthy.

**Comment by defeatedcrow** [comment]
I cannot fix this problem. This problem seems to be occurred by cause from another mod. This was caused by another mod including "incomplete" API package.
Incomplete API package is including package-info file, but lack some API class that must be included. It cause to malfunction of @Optional annotation.

In this case, Any other mod include incomplete API of CoFHCore, and cause this crash. Please report author of that mod.
Or, as another solution, please use CoFHCore.
